### ISSUE TITLE
FR: Case-agnostic URLs

### ISSUE THREAD

**Issue by isloat** [zxc23/dcss-scoreboard#11]
https://scoreboard.crawl.develz.org/players/Brannock.html
https://scoreboard.crawl.develz.org/players/brannock.html

**Comment by alexjurkiewicz** [comment]
On one hand this wouldn't be too hard, since player names are restricted to ascii letters/numbers and a few symbols. On the other hand, it requires Lua to run on every request:
https://dodwell.us/rewrite-uri-to-lowercase-using-nginxperl-nginxlua-or-apache.html
And where would users get upper-case URLs from? Manually entering them?

**Comment by isloat** [comment]
Already replied in irc, but leaving here for recording: my bookmarks were old and updating them fixes the issue. Probably a corner case, I don't suspect many other people having similar issues.

**Comment by alexjurkiewicz** [comment]
Closing issue. It would be nice for player names to be case agnostic but there's no good approach to this yet.
